import fs from 'fs-extra';
import path from 'path';
import { ProjectConfig } from '../types/index.js';
import { loadProjectConfig } from './frameworks.js';

/**
 * Generate React component files for logos
 */
export async function generateExportFile(projectPath: string = process.cwd()): Promise<void> {
  const projectConfig = await loadProjectConfig(projectPath);
  
  if (!projectConfig) {
    // No project config, skip generation
    return;
  }

  const logoDir = path.join(projectPath, projectConfig.logoDirectory);

  // Ensure logo directory exists
  if (!(await fs.pathExists(logoDir))) {
    return;
  }

  // Get all SVG files
  const files = await fs.readdir(logoDir);
  const svgFiles = files
    .filter(file => file.endsWith('.svg'))
    .sort()
    .map(file => ({
      filename: file,
      name: path.basename(file, '.svg'),
      key: path.basename(file, '.svg').toLowerCase().replace(/[^a-z0-9]/g, '')
    }));

  if (svgFiles.length === 0) {
    return;
  }

  // Generate single file with all React components
  await generateSingleComponentFile(svgFiles, projectConfig, projectPath);
}

/**
 * Generate a single file with all React components
 */
async function generateSingleComponentFile(
  svgFiles: Array<{ filename: string; name: string; key: string }>,
  projectConfig: ProjectConfig,
  projectPath: string
): Promise<void> {
  const logoDir = path.join(projectPath, projectConfig.logoDirectory);
  const isTypeScript = projectConfig.typescript;
  
  let content = `/**
 * Logo components - Auto-generated by LogoCN
 * Do not edit this file manually
 * 
 * Usage:
 *   import { ReactLogo } from '@/components/logos'
 *   <ReactLogo size={48} />
 */

import * as React from 'react'

`;

  // Add TypeScript interface if needed
  if (isTypeScript) {
    content += `export interface LogoProps extends React.SVGProps<SVGSVGElement> {
  size?: number | string
}

`;
  }

  // Generate each component
  for (const { filename, name, key } of svgFiles) {
    // Read SVG content
    const svgPath = path.join(logoDir, filename);
    const svgContent = await fs.readFile(svgPath, 'utf-8');
    
    // Clean up SVG content (remove <?xml> declaration if present)
    const cleanedSvg = svgContent.replace(/<\?xml.*?\?>/g, '').trim();
    
    // Generate component
    const componentName = `${capitalize(key)}Logo`;
    
    // Remove width/height from SVG if present
    let processedSvg = cleanedSvg
      .replace(/width="[^"]*"/g, '')
      .replace(/height="[^"]*"/g, '');
    
    // Add React props to SVG
    processedSvg = processedSvg.replace(
      /<svg([^>]*)>/,
      '<svg$1 width={width || size} height={height || size} {...props}>'
    );
    
    // Add component to content
    if (isTypeScript) {
      content += `export function ${componentName}({ 
  size = 24, 
  width, 
  height, 
  ...props 
}: LogoProps) {
  return (
    ${processedSvg}
  )
}

`;
    } else {
      content += `export function ${componentName}({ 
  size = 24, 
  width, 
  height, 
  ...props 
}) {
  return (
    ${processedSvg}
  )
}

`;
    }
  }
  
  // Write the single index file
  const indexFileName = isTypeScript ? 'index.tsx' : 'index.jsx';
  const indexPath = path.join(logoDir, indexFileName);
  await fs.writeFile(indexPath, content);
  
  // Clean up old individual component files if they exist
  for (const { key } of svgFiles) {
    const oldTsxPath = path.join(logoDir, `${key}.tsx`);
    const oldJsxPath = path.join(logoDir, `${key}.jsx`);
    if (await fs.pathExists(oldTsxPath)) {
      await fs.remove(oldTsxPath);
    }
    if (await fs.pathExists(oldJsxPath)) {
      await fs.remove(oldJsxPath);
    }
  }
  
  // Also remove old index.ts if it exists (we now use index.tsx)
  const oldIndexPath = path.join(logoDir, 'index.ts');
  if (await fs.pathExists(oldIndexPath) && isTypeScript) {
    await fs.remove(oldIndexPath);
  }
}

/**
 * Capitalize first letter
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Get the export file path for a project
 */
export async function getExportFilePath(projectPath: string = process.cwd()): Promise<string | null> {
  const projectConfig = await loadProjectConfig(projectPath);
  
  if (!projectConfig) {
    return null;
  }

  const indexFileName = projectConfig.typescript ? 'index.tsx' : 'index.jsx';
  return path.join(projectPath, projectConfig.logoDirectory, indexFileName);
}

/**
 * Check if export file exists
 */
export async function exportFileExists(projectPath: string = process.cwd()): Promise<boolean> {
  const exportFilePath = await getExportFilePath(projectPath);
  
  if (!exportFilePath) {
    return false;
  }

  return fs.pathExists(exportFilePath);
}